@startuml
actor "Gestor de Logística" as A
participant "<i><<System>></i>ElectricGo" as S

A -> S: Inicia o pedido de criacao de um Percurso
S --> A: Solicita os dados do Percurso\n<i>(Id do Armazém de Partida, Id do Armazém de Chegada,</i>\n<i>Distância, Tempo para percorrer, Energia para percorrer)</i>

A -> S: Fornece os dados do Percurso
S -> S: Verifica/valida os dados do Percurso
S -> S: Valida a existência dos Percurso
S -> S: Regista o Percurso
S --> A: Confirma que o Percurso foi criado com sucesso

@enduml
