@startuml
actor "Gestor de Frota" as A
participant "<i><<System>></i>ElectricGo" as S

A -> S: Inicia o pedido de criacao de um Empacotamento
S --> A: Solicita os dados do Empacotamento\n<i>(Posição X, Posição Y, Posição Z,</i>\n<i>Tempo de colocação, Tempo de retirada, ID da entrega)</i>

A -> S: Fornece os dados do Empacotamento
S -> S: Verifica/valida os dados do Empacotamento
S -> S: Regista o Empacotamento
S --> A: Confirma que o Empacotamento foi criado com sucesso
@enduml
