@startuml
actor "Gestor de Armazéns" as A
participant "<i><<System>></i>ElectricGo" as S

A -> S: Inicia o edicão de um Armazém
S --> A: Fornece a lista de Armazéns

A -> S: Seleciona o Armazém desejado
S --> A: Solicita os dados do Armazém\n(Designacao, Endereco, Coordenadas)

A -> S: Fornece os dados do Armazém
S -> S: Verifica/valida os dados do Armazém
S -> S: Regista o Armazém
S --> A: Confirma que o Armazém foi editado com sucesso

@enduml
